### ISSUE TITLE
Howto address "WARNING: POSSIBLE DNS SPOOFING DETECTED"

### ISSUE THREAD

**Issue by burntyellow** [pitt-crc/user-manual#67]
Ticket 165000

Whenever a remote host changes their keys for a particular IP address and that address had been cached locally, you will get a warning about potential DNS Spoofing.

Write a 1-page FAQ on how to solve this issue.

**Comment by leb140** [comment]
I added a FAQ section under docs/, containing a description and solution to the DNS Spoofing issue. Other common issues from tickets could be added in the future to docs/faq.md.
